### ISSUE TITLE
Crate versioning scheme requires all dependencies to use exactly same libbpf-sys version

### ISSUE THREAD

**Issue by kriomant** [libbpf/libbpf-sys#34]
I want to use both redbpf crate to load BPF programs and xsk-rs to handle packets on user-space side. I even initiated moving redbpf crate from using it's own libbpf bindings to using libbpf-sys. But now I still have a problem: redpbf and xsk-rs use different versions of libbpf-sys: ^0.6.1-2 and ^0.6.0-1 respectively.
Usually '^version' notation lets Cargo to choose newer version for both, but prerelease suffix, if I understand correctly, prevents it.

So, how can I use several crates depending on libbpf-sys? Requiring all of dependant crates to use exactly same version of libbpf-sys doesn't seem like a solution, any future update of any of crates will break my build.

**Comment by anakryiko** [comment]
Would it work better if libbpf-sys adopts a slightly different versions. Instead of 0.6.1-1, 0.6.1-2, etc, what if it has 0.6.1-libbpf.1, 0.6.1-libbpf.2, etc. That way, if all the libraries specify dependency on libbpf-sys as "0.6.1-libbpf", Cargo (according to how I understand the documentation) will pick the version with the largest X (numerically) in "0.6.1-libbpf.X".

@alexforster, @insearchoflosttime WDYT?

**Comment by kriomant** [comment]
If I understand correctly, `0.6.1-libbpf.1` will still be incompatible with `0.6.2-libbpf.1`.
Why not `0.6.1-1` → `0.0601.1`? This way `0.0601.1` will be compatible with `0.0602.2`. Major version is intentionally moved out, so that semver-incompatible libbpf versions will lead to semver-incompatible libbpf-sys versions.
It's not pretty, but should work. I can verify it, if you want.

**Comment by anakryiko** [comment]
I really don't like `0.0601.1`, it's hard to wrap your head around that, tbh.

From libbpf's standpoint 0.6.1 vs 0.6.2 shouldn't make much difference (we don't add new APIs in patch version). So excluding patch version from libbpf-sys versioning should be ok. So as another option, maybe libbpf-sys should share major.minor with libbpf, but use patch version as its own release? So 0.6.2, 0.6.3, etc can still refer to libbpf v0.6.1 (as an example). It's a bit confusing, of course, but libbpf patch version releases are very rare (I avoid them as much as possible), so just relying on latest libbpf-sys within a given libbpf's vmajor.minor should be a good strategy to get the latest best version within that major.minor version. But would be interesting to hear @alexforster thoughts, of course.

**Comment by kriomant** [comment]
Did you make a decision?

**Comment by alexforster** [comment]
When I first made this crate, I think libbpf was still in the `0.0.x` series, and there were relatively frequent ABI changes.  That's why I explicitly opted out of semver (see: _"you must not assume that any other version will be API or ABI compatible"_ in the `README`).

However, libbpf has long since been ABI stable, so I think we can try to become more semver-friendly now.

> So as another option, maybe libbpf-sys should share major.minor with libbpf, but use patch version as its own release?

I like this, plus a slight modification:

 * The major and minor versions will correspond to the respective `libbpf` versions.
 * The patch version will be "ours". It will not relate to libbpf.
 * We will additionally use the ["build metadata"](https://docs.rs/semver/1.0.7/semver/struct.BuildMetadata.html) to indicate the upstream `libbpf` tag (or commit) that is wrapped by a particular release.

For example, the next `libbpf-sys` release would be `0.7.0+v0.7.0`. Then, if I screw something up and have to cut another `libbpf-sys` release before upstream releases a new version, I'd bump `libbpf-sys` to `0.7.1+v0.7.0`.

**Comment by alexforster** [comment]
Note – I decided to publish the new version of the `v0.6` bindings using this new versioning scheme, so we are now officially semver compatible.

I'll have `v0.7` out soon...

**Comment by kriomant** [comment]
Thank you!
